# name: 'Tag a git version'
# description: 'Tagging a repo with a gitVersion'


# runs:
#   using: composite
#   steps:
#       # Git version steps:
#   - name: Install GitVersion
#     uses: gittools/actions/gitversion/setup@v0
#     with:
#       versionSpec: '5.x'
#   - name: Determine Version
#     id: gitversion
#     uses: gittools/actions/gitversion/execute@v0
#     with:
#       useConfigFile: true
#       configFilePath: gitversion.yml
#   - name: tag the repo
#     if: ${{ github.ref == 'refs/heads/main' }}
#     shell: bash
#     run: |
#       echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
#       echo ${{ env.semVer }}
#       git tag ${{ steps.gitversion.outputs.semVer }}
#       git push origin ${{ steps.gitversion.outputs.semVer }}
