name: GitVersion Tag

on:
  push:
    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Step
        uses: actions/checkout@v3
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.8
        with:
          inlineScript: |
            az account show
          # Azure CLI version to be used to execute the script. If not provided, latest version is used
          # azcliversion: # optional, default is agentazcliversion
