name: GitVersion Tag

# Expose workload identity, assign permissions in pipeline itself / differce from azure DevOps
permissions:
  id-token: write
  contents: write

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Step
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # we are referring to the remote repo
    - name: Tag GitVersion to repo
      uses: MKTHEPLUGG/gitversion-tag-action@v1
      with:
        configFilePath: gitversion.yml
        